{{- if .Values.jellyfin.nfs.config.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "jellyfin-helm-chart.fullname" . }}-nfs-config-pv
spec:
  capacity:
    storage: {{ .Values.jellyfin.nfs.config.size | default "5Gi" }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  volumeMode: Filesystem
  nfs:
    server: {{ required "jellyfin.nfs.server is required when an NFS volume is enabled" .Values.jellyfin.nfs.server }}
    path: {{ required "jellyfin.nfs.config.path is required" .Values.jellyfin.nfs.config.path }}
{{- end }}
