apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webserver.fullname" . }}-db
  labels:
    {{- include "webserver.labels" . | nindent 4 }}
type: Opaque
data:
  PAPERLESS_DBPASS: {{ .Values.paperlessVars.PAPERLESS_DBPASS  | b64enc | quote }}
  PAPERLESS_DBUSER: {{ .Values.paperlessVars.PAPERLESS_DBUSER  | b64enc | quote }}
