{{- if .Values.library.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ required "immich.immich.persistence.library.existingClaim is required" .Values.immich.immich.persistence.library.existingClaim }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.library.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.library.accessModes | nindent 4 }}
  {{- with .Values.library.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.library.size }}
{{- end }}
