apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustical.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rustical.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "rustical.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
