apiVersion: v2
name: home-assistant-helm-chart
description: Umbrella Chart for Home Assistant on K8s (NFS, CloudNativePG recorder database, Gateway API HTTPRoute)
type: application
version: 0.2.0
dependencies:
  - name: home-assistant
    version: 0.3.82
    repository: https://pajikos.github.io/home-assistant-helm-chart
